<a href="https://colab.research.google.com/github/leesangh92/homework/blob/main/(21_5_18)hw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

▶ 5월18일 도전 과제

1) 구구단을 2차원 배열로 만드시오. gdan
2) int16으로 자료형을 변경하시오.
 
3) 3단에만 50을 더하시오.
4) 5단에만 100을 곱하시오.
5) 모양을 어떤 형태든 다르게 변경하시오.

In [ ]:
dan = np.array([i for i in range(1, 10)])

In [ ]:
dan

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
g = [i * dan for i in range(1, 10)]

In [ ]:
g

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 3,  6,  9, 12, 15, 18, 21, 24, 27]),
 array([ 4,  8, 12, 16, 20, 24, 28, 32, 36]),
 array([ 5, 10, 15, 20, 25, 30, 35, 40, 45]),
 array([ 6, 12, 18, 24, 30, 36, 42, 48, 54]),
 array([ 7, 14, 21, 28, 35, 42, 49, 56, 63]),
 array([ 8, 16, 24, 32, 40, 48, 56, 64, 72]),
 array([ 9, 18, 27, 36, 45, 54, 63, 72, 81])]

In [ ]:
gdan = np.array([i * dan for i in range(1, 10)], dtype = np.int16)

In [ ]:
gdan

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]], dtype=int16)

In [ ]:
gdan[2] + 50

array([53, 56, 59, 62, 65, 68, 71, 74, 77], dtype=int16)

In [ ]:
gdan[4] * 100

array([ 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500], dtype=int16)

In [ ]:
gdan.reshape(1, 81)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  4,  6,  8, 10, 12, 14,
        16, 18,  3,  6,  9, 12, 15, 18, 21, 24, 27,  4,  8, 12, 16, 20,
        24, 28, 32, 36,  5, 10, 15, 20, 25, 30, 35, 40, 45,  6, 12, 18,
        24, 30, 36, 42, 48, 54,  7, 14, 21, 28, 35, 42, 49, 56, 63,  8,
        16, 24, 32, 40, 48, 56, 64, 72,  9, 18, 27, 36, 45, 54, 63, 72,
        81]], dtype=int16)