<a href="https://colab.research.google.com/github/leesangh92/homework/blob/main/(21_5_18)hw_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
np3 = np.arange(10, 241, 10)

In [ ]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [ ]:
np33 = np3.reshape(2, 12)

In [ ]:
np33

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [ ]:
np333 = np33.reshape(2, 3, 4)

In [ ]:
np333.shape

(2, 3, 4)

In [ ]:
np333

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [ ]:
np333[0][0][2]

30

In [ ]:
np333[0][2]

array([ 90, 100, 110, 120])

In [ ]:
np333[1:, 1:, :2]

array([[[170, 180],
        [210, 220]]])

In [ ]:
np64 = np333.reshape(6, 4)

In [ ]:
np64

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200],
       [210, 220, 230, 240]])

In [ ]:
np64[1:5, 2:]

array([[ 70,  80],
       [110, 120],
       [150, 160],
       [190, 200]])